#!/bin/bash
# /etc/init.d/carbon

### BEGIN INIT INFO
# Provides:		carbon
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop: 	0 1 6
# Short-Description:	Carbon
# Description:		This service is used to manage the Carbon daemon
### END INIT INFO


case "$1" in
	start)
		echo "Starting Carbon"
		/usr/bin/python /opt/graphite/bin/carbon-cache.py start
		;;

	stop)
		kill $(ps aux | grep '/opt/graphite/bin/carbon-cache.py' | grep -v 'grep' | awk '{ print $2 }')
		;;

	*)
		echo "Usage: /etc/init.d/carbon start|stop"
		exit 1
		;;
esac

exit 0
