#!/bin/bash
# /etc/init.d/graphite

### BEGIN INIT INFO
# Provides:		graphite
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop: 	0 1 6
# Short-Description:	Graphite
# Description:		This service is used to manage the Graphite web server
### END INIT INFO


case "$1" in
	start)
		echo "Starting Graphite"
		/usr/bin/python /opt/graphite/webapp/graphite/manage.py runserver --noreload 0.0.0.0:8000 > /dev/null 2>&1 &
		;;

	stop)
		kill $(ps aux | grep '/opt/graphite/webapp/graphite/manage.py' | grep -v 'grep' | awk '{ print $2 }')
		;;

	*)
		echo "Usage: /etc/init.d/graphite start|stop"
		exit 1
		;;
esac

exit 0
